---
# Configuration for Foreman Dynamic Inventory plugin (primary inventory for this environments)
plugin: theforeman.foreman.foreman

url: https://satellite.demolab.cz/
validate_certs: false 
user: ansible
password: ansible

#host_filters: 'parent_hostgroup="core/tst"'

want_content_facet_attributes: false # true
want_facts: false
want_host_group: true
want_hostcollections: true
want_ipv4: true
want_ipv6: false
want_location: true
want_organization: false
want_params: false
want_smart_proxies: true
want_subnet: false
want_subnet_v6: false


cache: true
cache_plugin: jsonfile
cache_connection: ./cache/
cache_timeout: 86400 # 1d

